# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  JWT : adventure
  FINANCE : ${{ secrets.FINANCE}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
<<<<<<< HEAD
  env:
  JWT: Monday
=======
    
>>>>>>> a5642721b351c40ae7e9d2fd6944a7b5602a26c3

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
<<<<<<< HEAD
    - run: npm start
=======
>>>>>>> a5642721b351c40ae7e9d2fd6944a7b5602a26c3
    
    - uses: actions/checkout@v3
      with:
        repository: gatofeles/financeTest
        path: financeTest
    
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - run: dotnet build tests
    
    - run: |
        npm start &
        sleep 2
        dotnet test tests
        kill -9 `lsof -i:3000 -t`

    
    
  

